Added feature to convert parameters to different units.
padaiyal/jAayvalar pull request #10
Opened 2021-05-02 16:02 UTC by the-c0d3br34k3r

## Description
Closes #7.
Added the following parameters with support to convert to different units:
 - Currency
 - Data storage
 - Distance
 - Measurable
 - Pressure
 - Temperature
 - Volume
 
## Author's Checklist
- [ ] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

2021-05-02 19:47 UTC, silvs110 requested changes
Shouldn't overriden methods have their own docstring?

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameter.java
> +          + ".\nCurrency unit should be exactly 3 letters.");
Internationalization

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameter.java
> +            "%s_%s",
This should be in the properties file.

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameter.java
> +        ).readNBytes(100) // The desired response should be way lesser than 100 bytes.
This should be in the properties file.

2021-05-02 19:47 UTC, silvs110 commented on src/test/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameterTest.java
> +  @ParameterizedTest
Missing docstring

2021-05-02 19:47 UTC, silvs110 commented on src/test/java/org/padaiyal/utilities/aayvalar/parameters/DataStorageParameterTest.java
> +public class DataStorageParameterTest
Missing tests docstrings

2021-05-02 19:47 UTC, silvs110 commented on src/test/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameterTest.java
> +  void testConvertToWithValidInputs(Double currentValue, String currentUnit, String resultUnit)
missing docstring

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/VolumeUnitEnum.java
> +public enum VolumeUnitEnum implements UnitTypeEnumInterface<Double> {
Missing docstrings

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/TemperatureUnitEnum.java
> +
Missing method docstrings

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/PressureUnitEnum.java
> +
missing method docstrings

2021-05-02 19:47 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/DistanceUnitEnum.java
> +
Missing method docstring

2021-05-02 19:51 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/PressureUnitEnum.java
> +
Skipped as it's an overridden method.

2021-05-02 19:51 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/TemperatureUnitEnum.java
> +
Skipped as they are overridden methods.

2021-05-02 19:51 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/VolumeUnitEnum.java
> +public enum VolumeUnitEnum implements UnitTypeEnumInterface<Double> {
Skipped as they are overridden methods.

2021-05-02 19:51 UTC, the-c0d3br34k3r commented on src/test/java/org/padaiyal/utilities/aayvalar/parameters/DataStorageParameterTest.java
> +public class DataStorageParameterTest
Skipped as they are overridden methods.

2021-05-02 19:53 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameter.java
> +          + ".\nCurrency unit should be exactly 3 letters.");
Done.

2021-05-02 19:55 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameter.java
> +            "%s_%s",
Done.

2021-05-02 19:56 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameter.java
> +        ).readNBytes(100) // The desired response should be way lesser than 100 bytes.
Done.

2021-05-02 23:06 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/aayvalar/parameters/units/DistanceUnitEnum.java
> +
Skipped as they are overridden methods.

2021-05-02 23:06 UTC, the-c0d3br34k3r commented on src/test/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameterTest.java
> +  void testConvertToWithValidInputs(Double currentValue, String currentUnit, String resultUnit)
Done.

2021-05-02 23:06 UTC, the-c0d3br34k3r commented on src/test/java/org/padaiyal/utilities/aayvalar/parameters/CurrencyParameterTest.java
> +  @ParameterizedTest
Done.

2021-05-03 00:18 UTC, silvs110 approved these changes

2021-05-03 00:30 UTC, merged